module org.example.asm2_insurance_claim_management_system {
    requires javafx.controls;
    requires javafx.fxml;
    requires jakarta.persistence;
    requires org.hibernate.orm.core;
    requires java.naming;

    opens org.example.asm2_insurance_claim_management_system to javafx.fxml, org.hibernate.orm.core;
    exports org.example.asm2_insurance_claim_management_system;
    exports org.example.asm2_insurance_claim_management_system.Admin;
    opens org.example.asm2_insurance_claim_management_system.Admin to javafx.fxml, org.hibernate.orm.core;
    exports org.example.asm2_insurance_claim_management_system.Login;
    opens org.example.asm2_insurance_claim_management_system.Login to javafx.fxml, org.hibernate.orm.core;
    exports org.example.asm2_insurance_claim_management_system.Interface;
    opens org.example.asm2_insurance_claim_management_system.Interface to javafx.fxml, org.hibernate.orm.core;
    exports org.example.asm2_insurance_claim_management_system.Customers;
    opens org.example.asm2_insurance_claim_management_system.Customers to javafx.fxml, org.hibernate.orm.core;
    exports org.example.asm2_insurance_claim_management_system.Providers;
    opens org.example.asm2_insurance_claim_management_system.Providers to javafx.fxml, org.hibernate.orm.core;
    exports org.example.asm2_insurance_claim_management_system.InsuranceCard;
    opens org.example.asm2_insurance_claim_management_system.InsuranceCard to javafx.fxml, org.hibernate.orm.core;
    exports org.example.asm2_insurance_claim_management_system.Claim;
    opens org.example.asm2_insurance_claim_management_system.Claim to javafx.fxml, org.hibernate.orm.core;
    exports org.example.asm2_insurance_claim_management_system.System;
    opens org.example.asm2_insurance_claim_management_system.System to javafx.fxml, org.hibernate.orm.core;
    exports org.example.asm2_insurance_claim_management_system.AdminGUI;
    opens org.example.asm2_insurance_claim_management_system.AdminGUI to javafx.fxml, org.hibernate.orm.core;
    exports org.example.asm2_insurance_claim_management_system.Alert;
    opens org.example.asm2_insurance_claim_management_system.Alert to javafx.fxml, org.hibernate.orm.core;
    exports org.example.asm2_insurance_claim_management_system.PolicyHolderGUI to javafx.fxml;
    opens org.example.asm2_insurance_claim_management_system.PolicyHolderGUI to javafx.fxml;
    exports org.example.asm2_insurance_claim_management_system.PolicyOwnerGUI to javafx.fxml;
    opens org.example.asm2_insurance_claim_management_system.PolicyOwnerGUI to javafx.fxml;
    exports org.example.asm2_insurance_claim_management_system.DependentGUI;
    opens org.example.asm2_insurance_claim_management_system.DependentGUI to javafx.fxml, org.hibernate.orm.core;
    exports org.example.asm2_insurance_claim_management_system.SurveyorGUI;
    opens org.example.asm2_insurance_claim_management_system.SurveyorGUI to javafx.fxml, org.hibernate.orm.core;
    exports org.example.asm2_insurance_claim_management_system.ManagerGUI;
    opens org.example.asm2_insurance_claim_management_system.ManagerGUI to javafx.fxml, org.hibernate.orm.core;
}